### ISSUE TITLE
Asking about test format EpiSurfEmb

### ISSUE THREAD

**Issue by khanh0812** [rasmushaugaard/episurfemb#1]
HI Ramus, many thanks for your great work. I am testing with EpiSurfEmb, could you please provide some explanation how to set up the test data??
for tgt in json.load((dataset_root / 'test_targets_bop19.json').open()):
    target_count_dict[(tgt['scene_id'], tgt['im_id'], tgt['obj_id'])] = tgt['inst_count']

I see in your code, there is a file "test_targets_bop19.json", what is the content of this file? and if I would like to use camera, how can I set up the input?

Many thanks for your response

**Comment by rasmushaugaard** [comment]
Hi 

`test_targets_bop19.json` comes with the [bop datasets](https://bop.felk.cvut.cz/datasets/)
I you want to use a camera, have a look at `infer_multiview.py` to see, how images should be fed to the model.

BR, Rasmus

**Comment by khanh0812** [comment]
Many thanks, it works
